### PR TITLE
Using JSON as arguments for scripts

### PR DESCRIPTION
**Pull request by Cerfoglg**
Related to https://github.com/benchflow/data-transformers/issues/67

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/benchflow/analysers/pull/73%23issuecomment-221889183%22%2C%20%22https%3A//github.com/benchflow/analysers/pull/73%23issuecomment-221960123%22%2C%20%22https%3A//github.com/benchflow/analysers/pull/73%23issuecomment-221960179%22%2C%20%22https%3A//github.com/benchflow/analysers/pull/73%23issuecomment-222081331%22%2C%20%22https%3A//github.com/benchflow/analysers/pull/73%23issuecomment-222083721%22%2C%20%22https%3A//github.com/benchflow/analysers/pull/73%23issuecomment-222092363%22%2C%20%22https%3A//github.com/benchflow/analysers/pull/73%23issuecomment-222098046%22%2C%20%22https%3A//github.com/benchflow/analysers/pull/73%23issuecomment-222105055%22%2C%20%22https%3A//github.com/benchflow/analysers/pull/73%23issuecomment-222105979%22%2C%20%22https%3A//github.com/benchflow/analysers/pull/73%23issuecomment-222108367%22%2C%20%22https%3A//github.com/benchflow/analysers/pull/73%23issuecomment-222111214%22%2C%20%22https%3A//github.com/benchflow/analysers/pull/73%23issuecomment-222470260%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/benchflow/analysers/pull/73%23issuecomment-221889183%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%21%5BCodacy%5D%28https%3A//www.codacy.com/assets/images/favicon.png%29%20Here%20is%20an%20overview%20of%20what%20got%20changed%20by%20this%20pull%20request%3A%5Cn%5Cn%5Cn%60%60%60diff%5Cn%5CnClones%20added%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn-%20analysers/trials/cpu.py%20%201%5Cn-%20analysers/experiments/throughput.py%20%201%5Cn-%20analysers/experiments/ram.py%20%201%5Cn-%20analysers/experiments/databaseSize.py%20%201%5Cn-%20analysers/experiments/cpu.py%20%202%5Cn%20%20%20%20%20%20%20%20%20%5Cn%5CnClones%20removed%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%2B%20analysers/experiments/IO.py%20%20-2%5Cn%20%20%20%20%20%20%20%20%20%5Cn%60%60%60%5Cn%5Cn%5CnSee%20the%20complete%20overview%20on%20%5BCodacy%5D%28https%3A//www.codacy.com/app/BenchFlow/analysers/pullRequest%3Fprid%3D244635%26bid%3D3321132%29%5Cn%20%20%20%20%20%20%20%20%22%2C%20%22created_at%22%3A%20%222016-05-26T14%3A35%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22Does%20not%20build%22%2C%20%22created_at%22%3A%20%222016-05-26T18%3A48%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22Map%20the%20issues%2C%20as%20usual%22%2C%20%22created_at%22%3A%20%222016-05-26T18%3A48%3A42Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%21%5BCodacy%5D%28https%3A//www.codacy.com/assets/images/favicon.png%29%20Here%20is%20an%20overview%20of%20what%20got%20changed%20by%20this%20pull%20request%3A%5Cn%5Cn%5Cn%60%60%60diff%5Cn%5CnClones%20added%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn-%20analysers/trials/cpu.py%20%201%5Cn-%20analysers/experiments/throughput.py%20%201%5Cn-%20analysers/experiments/ram.py%20%201%5Cn-%20analysers/experiments/databaseSize.py%20%201%5Cn-%20analysers/experiments/cpu.py%20%202%5Cn%20%20%20%20%20%20%20%20%20%5Cn%5CnClones%20removed%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%2B%20analysers/experiments/IO.py%20%20-2%5Cn%20%20%20%20%20%20%20%20%20%5Cn%60%60%60%5Cn%5Cn%5CnSee%20the%20complete%20overview%20on%20%5BCodacy%5D%28https%3A//www.codacy.com/app/BenchFlow/analysers/pullRequest%3Fprid%3D244635%26bid%3D3321132%29%5Cn%20%20%20%20%20%20%20%20%22%2C%20%22created_at%22%3A%20%222016-05-27T07%3A41%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%21%5BCodacy%5D%28https%3A//www.codacy.com/assets/images/favicon.png%29%20Here%20is%20an%20overview%20of%20what%20got%20changed%20by%20this%20pull%20request%3A%5Cn%5Cn%5Cn%60%60%60diff%5Cn%5CnClones%20added%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn-%20analysers/trials/ram.py%20%201%5Cn-%20analysers/trials/cpu.py%20%201%5Cn-%20analysers/trials/IO.py%20%201%5Cn-%20analysers/experiments/ram.py%20%201%5Cn-%20analysers/experiments/cpu.py%20%201%5Cn%20%20%20%20%20%20%20%20%20%5Cn%5CnClones%20removed%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%2B%20analysers/experiments/IO.py%20%20-1%5Cn%20%20%20%20%20%20%20%20%20%5Cn%60%60%60%5Cn%5Cn%5CnSee%20the%20complete%20overview%20on%20%5BCodacy%5D%28https%3A//www.codacy.com/app/BenchFlow/analysers/pullRequest%3Fprid%3D244635%26bid%3D3321132%29%5Cn%20%20%20%20%20%20%20%20%22%2C%20%22created_at%22%3A%20%222016-05-27T07%3A54%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%21%5BCodacy%5D%28https%3A//www.codacy.com/assets/images/favicon.png%29%20Here%20is%20an%20overview%20of%20what%20got%20changed%20by%20this%20pull%20request%3A%5Cn%5Cn%5Cn%60%60%60diff%5Cn%5CnClones%20added%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn-%20analysers/trials/ram.py%20%201%5Cn-%20analysers/trials/cpu.py%20%201%5Cn-%20analysers/trials/IO.py%20%201%5Cn-%20analysers/experiments/ram.py%20%201%5Cn-%20analysers/experiments/cpu.py%20%201%5Cn%20%20%20%20%20%20%20%20%20%5Cn%5CnClones%20removed%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%2B%20analysers/experiments/IO.py%20%20-1%5Cn%20%20%20%20%20%20%20%20%20%5Cn%60%60%60%5Cn%5Cn%5CnSee%20the%20complete%20overview%20on%20%5BCodacy%5D%28https%3A//www.codacy.com/app/BenchFlow/analysers/pullRequest%3Fprid%3D244635%26bid%3D3321132%29%5Cn%20%20%20%20%20%20%20%20%22%2C%20%22created_at%22%3A%20%222016-05-27T08%3A39%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%21%5BCodacy%5D%28https%3A//www.codacy.com/assets/images/favicon.png%29%20Here%20is%20an%20overview%20of%20what%20got%20changed%20by%20this%20pull%20request%3A%5Cn%5Cn%5Cn%60%60%60diff%5Cn%5CnClones%20added%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn-%20analysers/trials/ram.py%20%201%5Cn-%20analysers/trials/cpu.py%20%201%5Cn-%20analysers/trials/IO.py%20%201%5Cn-%20analysers/experiments/ram.py%20%201%5Cn-%20analysers/experiments/cpu.py%20%201%5Cn%20%20%20%20%20%20%20%20%20%5Cn%5CnClones%20removed%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%2B%20analysers/experiments/IO.py%20%20-1%5Cn%20%20%20%20%20%20%20%20%20%5Cn%60%60%60%5Cn%5Cn%5CnSee%20the%20complete%20overview%20on%20%5BCodacy%5D%28https%3A//www.codacy.com/app/BenchFlow/analysers/pullRequest%3Fprid%3D244635%26bid%3D3321132%29%5Cn%20%20%20%20%20%20%20%20%22%2C%20%22created_at%22%3A%20%222016-05-27T09%3A08%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%21%5BCodacy%5D%28https%3A//www.codacy.com/assets/images/favicon.png%29%20Here%20is%20an%20overview%20of%20what%20got%20changed%20by%20this%20pull%20request%3A%5Cn%5Cn%5Cn%60%60%60diff%5Cn%5CnClones%20added%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn-%20analysers/experiments/throughput.py%20%201%5Cn-%20analysers/experiments/ram.py%20%202%5Cn-%20analysers/experiments/databaseSize.py%20%201%5Cn-%20analysers/experiments/cpu.py%20%201%5Cn%20%20%20%20%20%20%20%20%20%5Cn%5CnClones%20removed%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%2B%20analysers/trials/cpu.py%20%20-1%5Cn%2B%20analysers/experiments/IO.py%20%20-2%5Cn%20%20%20%20%20%20%20%20%20%5Cn%60%60%60%5Cn%5Cn%5CnSee%20the%20complete%20overview%20on%20%5BCodacy%5D%28https%3A//www.codacy.com/app/BenchFlow/analysers/pullRequest%3Fprid%3D244635%26bid%3D3321132%29%5Cn%20%20%20%20%20%20%20%20%22%2C%20%22created_at%22%3A%20%222016-05-27T09%3A43%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%21%5BCodacy%5D%28https%3A//www.codacy.com/assets/images/favicon.png%29%20Here%20is%20an%20overview%20of%20what%20got%20changed%20by%20this%20pull%20request%3A%5Cn%5Cn%5Cn%60%60%60diff%5Cn%5CnClones%20added%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn-%20analysers/trials/cpu.py%20%201%5Cn-%20analysers/experiments/ram.py%20%202%5Cn-%20analysers/experiments/cpu.py%20%201%5Cn%20%20%20%20%20%20%20%20%20%5Cn%5CnClones%20removed%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%2B%20analysers/experiments/IO.py%20%20-2%5Cn%20%20%20%20%20%20%20%20%20%5Cn%60%60%60%5Cn%5Cn%5CnSee%20the%20complete%20overview%20on%20%5BCodacy%5D%28https%3A//www.codacy.com/app/BenchFlow/analysers/pullRequest%3Fprid%3D244635%26bid%3D3321132%29%5Cn%20%20%20%20%20%20%20%20%22%2C%20%22created_at%22%3A%20%222016-05-27T09%3A47%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%21%5BCodacy%5D%28https%3A//www.codacy.com/assets/images/favicon.png%29%20Here%20is%20an%20overview%20of%20what%20got%20changed%20by%20this%20pull%20request%3A%5Cn%5Cn%5Cn%60%60%60diff%5Cn%5CnClones%20added%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn-%20analysers/trials/cpu.py%20%201%5Cn-%20analysers/experiments/throughput.py%20%201%5Cn-%20analysers/experiments/ram.py%20%201%5Cn-%20analysers/experiments/databaseSize.py%20%201%5Cn-%20analysers/experiments/cpu.py%20%202%5Cn%20%20%20%20%20%20%20%20%20%5Cn%5CnClones%20removed%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%2B%20analysers/experiments/IO.py%20%20-2%5Cn%20%20%20%20%20%20%20%20%20%5Cn%60%60%60%5Cn%5Cn%5CnSee%20the%20complete%20overview%20on%20%5BCodacy%5D%28https%3A//www.codacy.com/app/BenchFlow/analysers/pullRequest%3Fprid%3D244635%26bid%3D3321132%29%5Cn%20%20%20%20%20%20%20%20%22%2C%20%22created_at%22%3A%20%222016-05-27T09%3A59%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%21%5BCodacy%5D%28https%3A//www.codacy.com/assets/images/favicon.png%29%20Here%20is%20an%20overview%20of%20what%20got%20changed%20by%20this%20pull%20request%3A%5Cn%5Cn%5Cn%60%60%60diff%5Cn%5CnClones%20added%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn-%20analysers/trials/IO.py%20%201%5Cn-%20analysers/experiments/ram.py%20%201%5Cn-%20analysers/experiments/cpu.py%20%202%5Cn%20%20%20%20%20%20%20%20%20%5Cn%5CnClones%20removed%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%2B%20analysers/experiments/IO.py%20%20-2%5Cn%20%20%20%20%20%20%20%20%20%5Cn%60%60%60%5Cn%5Cn%5CnSee%20the%20complete%20overview%20on%20%5BCodacy%5D%28https%3A//www.codacy.com/app/BenchFlow/analysers/pullRequest%3Fprid%3D244635%26bid%3D3321132%29%5Cn%20%20%20%20%20%20%20%20%22%2C%20%22created_at%22%3A%20%222016-05-27T10%3A14%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40VincenzoFerme%20This%20should%20be%20good%20now%22%2C%20%22created_at%22%3A%20%222016-05-30T11%3A14%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8819678%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Cerfoglg%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/benchflow/analysers/pull/73#issuecomment-221889183'>General Comment</a></b>
- <a href='https://github.com/Cerfoglg'></a> @VincenzoFerme This should be good now

<a href='https://www.codereviewhub.com/benchflow/analysers/pull/73?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/benchflow/analysers/pull/73?approve=1'></a>&nbsp;<a href='https://github.com/benchflow/analysers/pull/73'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by VincenzoFerme** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/benchflow/analysers/pull/73'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by VincenzoFerme** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- analysers/trials/cpu.py  1
- analysers/experiments/throughput.py  1
- analysers/experiments/ram.py  1
- analysers/experiments/databaseSize.py  1
- analysers/experiments/cpu.py  2
         

Clones removed
==============
+ analysers/experiments/IO.py  -2
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/BenchFlow/analysers/pullRequest?prid=244635&bid=3321132)

**Comment by VincenzoFerme** [comment]
Does not build

**Comment by VincenzoFerme** [comment]
Map the issues, as usual

**Comment by VincenzoFerme** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- analysers/trials/cpu.py  1
- analysers/experiments/throughput.py  1
- analysers/experiments/ram.py  1
- analysers/experiments/databaseSize.py  1
- analysers/experiments/cpu.py  2
         

Clones removed
==============
+ analysers/experiments/IO.py  -2
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/BenchFlow/analysers/pullRequest?prid=244635&bid=3321132)

**Comment by VincenzoFerme** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- analysers/trials/ram.py  1
- analysers/trials/cpu.py  1
- analysers/trials/IO.py  1
- analysers/experiments/ram.py  1
- analysers/experiments/cpu.py  1
         

Clones removed
==============
+ analysers/experiments/IO.py  -1
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/BenchFlow/analysers/pullRequest?prid=244635&bid=3321132)

**Comment by VincenzoFerme** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- analysers/trials/ram.py  1
- analysers/trials/cpu.py  1
- analysers/trials/IO.py  1
- analysers/experiments/ram.py  1
- analysers/experiments/cpu.py  1
         

Clones removed
==============
+ analysers/experiments/IO.py  -1
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/BenchFlow/analysers/pullRequest?prid=244635&bid=3321132)

**Comment by VincenzoFerme** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- analysers/trials/ram.py  1
- analysers/trials/cpu.py  1
- analysers/trials/IO.py  1
- analysers/experiments/ram.py  1
- analysers/experiments/cpu.py  1
         

Clones removed
==============
+ analysers/experiments/IO.py  -1
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/BenchFlow/analysers/pullRequest?prid=244635&bid=3321132)

**Comment by VincenzoFerme** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- analysers/experiments/throughput.py  1
- analysers/experiments/ram.py  2
- analysers/experiments/databaseSize.py  1
- analysers/experiments/cpu.py  1
         

Clones removed
==============
+ analysers/trials/cpu.py  -1
+ analysers/experiments/IO.py  -2
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/BenchFlow/analysers/pullRequest?prid=244635&bid=3321132)

**Comment by VincenzoFerme** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- analysers/trials/cpu.py  1
- analysers/experiments/ram.py  2
- analysers/experiments/cpu.py  1
         

Clones removed
==============
+ analysers/experiments/IO.py  -2
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/BenchFlow/analysers/pullRequest?prid=244635&bid=3321132)

**Comment by VincenzoFerme** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- analysers/trials/cpu.py  1
- analysers/experiments/throughput.py  1
- analysers/experiments/ram.py  1
- analysers/experiments/databaseSize.py  1
- analysers/experiments/cpu.py  2
         

Clones removed
==============
+ analysers/experiments/IO.py  -2
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/BenchFlow/analysers/pullRequest?prid=244635&bid=3321132)

**Comment by VincenzoFerme** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- analysers/trials/IO.py  1
- analysers/experiments/ram.py  1
- analysers/experiments/cpu.py  2
         

Clones removed
==============
+ analysers/experiments/IO.py  -2
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/BenchFlow/analysers/pullRequest?prid=244635&bid=3321132)

**Comment by Cerfoglg** [comment]
@VincenzoFerme This should be good now

**Pull request merged**
