### PR TITLE
Using container names when necessary

### PR DESCRIPTION
**Pull request by Cerfoglg**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/benchflow/analysers/pull/89%23issuecomment-235545242%22%2C%20%22https%3A//github.com/benchflow/analysers/pull/89%23issuecomment-235548213%22%2C%20%22https%3A//github.com/benchflow/analysers/pull/89%23issuecomment-235558755%22%2C%20%22https%3A//github.com/benchflow/analysers/pull/89%23issuecomment-235645130%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/benchflow/analysers/pull/89%23issuecomment-235545242%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40Cerfoglg%20you%20also%20need%20to%20use%20the%20%60host_id%60%20paired%20with%20the%20%60container_name%60%22%2C%20%22created_at%22%3A%20%222016-07-27T10%3A15%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40VincenzoFerme%20We%20don%27t%20need%20it%20where%20we%20use%20container%20name%2C%20the%20host%20id%20is%20paired%20with%20container%20ID%20mainly%20for%20the%20container%20properties%20table%20and%20identifying%20unique%20containers.%5Cr%5Cn%5Cr%5CnAlso%2C%20due%20to%20how%20Cassandra%20queries%20work%2C%20if%20we%20use%20both%20we%20end%20up%20having%20problems%20performing%20selects%22%2C%20%22created_at%22%3A%20%222016-07-27T10%3A30%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8819678%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Cerfoglg%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40VincenzoFerme%20Corrected%20back%20to%20using%20host%20id%2C%20see%20also%20here%20https%3A//github.com/benchflow/docker-images/pull/19%22%2C%20%22created_at%22%3A%20%222016-07-27T11%3A27%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8819678%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Cerfoglg%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-07-27T16%3A40%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7163641%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/VincenzoFerme%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/benchflow/analysers/pull/89#issuecomment-235545242'>General Comment</a></b>
- <a href='https://github.com/VincenzoFerme'></a> @Cerfoglg you also need to use the `host_id` paired with the `container_name`
- <a href='https://github.com/Cerfoglg'></a> @VincenzoFerme We don't need it where we use container name, the host id is paired with container ID mainly for the container properties table and identifying unique containers.
  Also, due to how Cassandra queries work, if we use both we end up having problems performing selects
- <a href='https://github.com/Cerfoglg'></a> @VincenzoFerme Corrected back to using host id, see also here https://github.com/benchflow/docker-images/pull/19

<a href='https://www.codereviewhub.com/benchflow/analysers/pull/89?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/benchflow/analysers/pull/89?approve=1'></a>&nbsp;<a href='https://github.com/benchflow/analysers/pull/89'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by VincenzoFerme** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/benchflow/analysers/pull/89'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by VincenzoFerme** [comment]
@Cerfoglg you also need to use the `host_id` paired with the `container_name`

**Comment by Cerfoglg** [comment]
@VincenzoFerme We don't need it where we use container name, the host id is paired with container ID mainly for the container properties table and identifying unique containers.

Also, due to how Cassandra queries work, if we use both we end up having problems performing selects

**Comment by Cerfoglg** [comment]
@VincenzoFerme Corrected back to using host id, see also here https://github.com/benchflow/docker-images/pull/19

**Comment by VincenzoFerme** [comment]
:+1:

**Pull request merged**
